### ISSUE TITLE
Investigate DDEV project type config

### ISSUE THREAD

**Issue by paul121** [paul121/farmos-ddev-template#2]
Would be easier if we could say `ddev create --project-type farmOS`

**Comment by wotnak** [comment]
New project types currently can only be defined in ddev code https://ddev.readthedocs.io/en/latest/developers/project-types/. I don't know if contributing a custom one for farmOS would be accepted, since it would be almost exactly the same as the drupal one. 

DDEV allows however to [create addons](https://ddev.readthedocs.io/en/latest/users/extend/additional-services/#creating-an-additional-service-for-ddev-get) that can be installed using `ddev get <addon>` command. Custom addon can for example be used to simplify php-geos installation https://github.com/wotnak/ddev-php-geos https://github.com/farmOS/farmOS-community-blog/issues/18#issuecomment-1550284603 or extend/modify any other project aspect.

**Comment by paul121** [comment]
Amazing @wotnak ! That is great. I agree we don't need a custom project type then, the addon is sufficient. Once I test I'll prob update this readme and archive this repo...

**Comment by paul121** [comment]
Use [wotnak/ddev-php-geos](https://github.com/wotnak/ddev-php-geos) `ddev get wotnak/ddev-php-geos`
